apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: nginx-setup
        image: nginx:1.14.2
        env:
        - name: BF_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command: [ "/bin/sh" ]
        args: [ "-c", 'cp /usr/share/nginx/html/index.html /work-dir; sed -i "s/Welcome to nginx/Welcome to nginx on ${BF_NODE_NAME}/g" /work-dir/index.html' ]
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
      volumes:
      - name: workdir
        emptyDir: {}
